### ISSUE TITLE
BACKGROUND LOCATION NOT WORKING AFTER 5 MINUTES 

### ISSUE THREAD

**Issue by ivinantony** [capacitor-community/background-geolocation#94]
**Describe the bug**
i was testing the plugin and it works well in ios and in some android. i was testing in google pixel 5 and after 5 minutes there is no response from the plugin when app in background and the screen is locked. i tested multiple devices [samsung m13 and pixel 5] both have the same issue.When we unlock the device and open the app, all the locations that were not updated coming in the console too.

**To Reproduce**
open the app in google pixel r real  or Samsung m13 device-> activate background geolocation-> put the app to background -> lock the screen.

**Expected behavior**
it should sent the data even its locked.

**Screenshots**

<img width="1421" alt="Screenshot 2023-02-28 at 6 04 04 PM" src="https://user-images.githubusercontent.com/66516836/221855384-6a94d909-d311-481d-8dda-13e35264957c.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
i am optimized the battery using battery optimization plugin already.
Warning IN ANDROID STUDIO 

2023-02-28 18:01:52.898 11870-12369 MessageQueue            io.ionic.starter                     W  Handler (com.google.android.gms.common.api.internal.ListenerHolder$zaa) {934c5a0} sending message to a Handler on a dead thread
                                                                                                    java.lang.IllegalStateException: Handler (com.google.android.gms.common.api.internal.ListenerHolder$zaa) {934c5a0} sending message to a Handler on a dead thread
                                                                                                    	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
                                                                                                    	at android.os.Handler.enqueueMessage(Handler.java:778)
                                                                                                    	at android.os.Handler.sendMessageAtTime(Handler.java:727)
                                                                                                    	at android.os.Handler.sendMessageDelayed(Handler.java:697)
                                                                                                    	at android.os.Handler.sendMessage(Handler.java:635)
                                                                                                    	at com.google.android.gms.common.api.internal.ListenerHolder.notifyListener(Unknown Source:8)
                                                                                                    	at com.google.android.gms.internal.location.zzat.onLocationResult(Unknown Source:7)
                                                                                                    	at com.google.android.gms.location.zzv.dispatchTransaction(Unknown Source:25)
                                                                                                    	at com.google.android.gms.internal.location.zzb.onTransact(Unknown Source:22)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1321)

**Comment by ivinantony** [comment]
@diachedelic  it seems working fine after your code you sent me above. thanks alot. can you make a new version with this change asap?

**Comment by diachedelic** [comment]
Please test that this is fixed in v1.2.12.
